/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'url' : string,
  'title' : string,
  'source' : string,
  'body' : string,
  'published_on' : Time,
  'imageurl' : string,
}
export interface Coin {
  'name' : string,
  'price_usd' : number,
  'symbol' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'getArticlesBySources' : ActorMethod<[Array<string>], Array<Article>>,
  'getArticlesSince' : ActorMethod<[Time], Array<Article>>,
  'getCoinBySymbol' : ActorMethod<[string], [] | [Coin]>,
  'getNews' : ActorMethod<[], Array<Article>>,
  'getNewsByKeyword' : ActorMethod<[string], Array<Article>>,
  'getNewsBySource' : ActorMethod<[string], Array<Article>>,
  'getPrices' : ActorMethod<[], Array<Coin>>,
  'getTopArticles' : ActorMethod<[bigint], Array<Article>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];